services:
  fintrace-ec2:
    build:
      context: .
      dockerfile: Dockerfile.ec2
    image: fintrace-ec2:latest
    container_name: fintrace-ec2
    ports:
      - "3004:3004"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fintrace-network

  fintrace-ec2-2:
    build:
      context: .
      dockerfile: Dockerfile.ec2
    image: fintrace-ec2:latest
    container_name: fintrace-ec2-2
    ports:
      - "3005:3004"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fintrace-network

  fintrace-ec2-3:
    build:
      context: .
      dockerfile: Dockerfile.ec2
    image: fintrace-ec2:latest
    container_name: fintrace-ec2-3
    ports:
      - "3006:3004"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fintrace-network

networks:
  fintrace-network:
    driver: bridge
