version: "3.8"
services:
  fintrace-api:
    build: .
    image: fintrace-lambda:latest
    container_name: fintrace-api
    ports:
      - "3200:3000"
    env_file:
      - .env
    # Si necesitas montar archivos locales, descomenta:
    # volumes:
    #   - ./src/template:/app/src/template
