version: "3.8"
services:
  fintrace-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    image: fintrace-dev:latest
    container_name: fintrace-dev
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - PORT=3004
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fintrace-network

networks:
  fintrace-network:
    driver: bridge
